# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "article_view_logs", :force => true do |t|
    t.column "article_id", :integer
    t.column "user_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "articles", :force => true do |t|
    t.column "subject", :string
    t.column "url", :string
    t.column "body", :text
    t.column "access_count", :integer, :default => 0
    t.column "access_date", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "user_id", :integer
    t.column "modified_at", :datetime, :null => false
    t.column "url_access_at", :datetime
  end

  create_table "articles_tags", :id => false, :force => true do |t|
    t.column "article_id", :integer
    t.column "tag_id", :integer
  end

  create_table "bars", :force => true do |t|
    t.column "body", :text
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "settings", :force => true do |t|
    t.column "var", :string, :null => false
    t.column "value", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "user_infos", :force => true do |t|
    t.column "user_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "name_kanji1", :string, :default => "", :null => false
    t.column "name_kanji2", :string, :default => "", :null => false
    t.column "pc_email", :string, :default => "", :null => false
    t.column "mobile_email", :string, :default => "", :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "karma", :integer, :default => 0
  end

  create_table "users", :force => true do |t|
    t.column "loginname", :string, :default => "", :null => false
    t.column "password", :string, :default => "", :null => false
    t.column "deleted", :boolean, :default => false, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
